branch-defaults:
  master:
    environment: loanhero-api-newqa-demo
environment-defaults:
  loanhero-api-newqa-demo:
    branch: null
    repository: null
global:
  application_name: LoanHero API
  default_ec2_keyname: developer
  default_platform: arn:aws:elasticbeanstalk:us-west-1::platform/Puma with Ruby 2.3
    running on 64bit Amazon Linux/2.6.0
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
